global:
  scrape_interval: 5s  # Check every 5 seconds

scrape_configs:
  - job_name: 'credit-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']  # local Spring Boot app
